// Copyright (c) 2026 Sub Rosa contributors
import { describe, it } from "node:test";
import assert from "node:assert/strict";
import * as sdk from "./index.js";

const EXPECTED_EXPORTS = [
  "ASSET_FIXTURES",
  "AssetConfigError",
  "DEPLOYMENT_CHECK_IDS",
  "DEPLOYMENT_FIELDS",
  "DEPLOYMENT_FIELD_LABELS",
  "ACTIVE_ROUND_STATUSES",
  "ERROR_ROUND_STATUSES",
  "KeeperStatusClient",
  "MAINNET_ARTIFACTS",
  "MAINNET_MANIFEST",
  "MAINNET_MANIFEST_PATH",
  "MAINNET_XLM_SAC_ID",
  "MAINNET_CONFIRM_PHRASE",
  "MAINNET_DEPLOY_MIN_XLM_STROOPS",
  "MAINNET_MICRO_MAX_ESCROW",
  "MAINNET_MIN_FEE_RESERVE_STROOPS",
  "MAX_AUDITOR_BLOB_BYTES",
  "MAX_CIPHERTEXT_BYTES",
  "RECEIPT_VERSION",
  "RoundContract",
  "RoundErrors",
  "StatusApiError",
  "StatusJsonParseError",
  "SubRosaClient",
  "SubRosaClientConfigError",
  "SubRosaDeploymentMismatchError",
  "SubRosaManifestError",
  "SubRosaMissingReturnValueError",
  "SubRosaNetworkMismatchError",
  "SubRosaPreflightError",
  "SubRosaSubmitError",
  "SubRosaTimeoutError",
  "SubRosaTransactionError",
  "TERMINAL_ROUND_STATUSES",
  "assertDeploymentMatches",
  "assertMainnetConfirmed",
  "assertMicroAmounts",
  "assertReadinessForExecute",
  "classifyRoundStatus",
  "contractErrorCode",
  "createOzChannelsSubmitter",
  "createOzChannelsSubmitterFromEnv",
  "compareDeployment",
  "createSacBalanceReader",
  "defaultMainnetReadinessInput",
  "deploymentChecks",
  "evaluatePreflight",
  "fetchContractWasmHash",
  "fetchKeeperStatus",
  "fixtureDeployment",
  "fixtureReader",
  "formatReadinessReport",
  "hasBlockingFailures",
  "isActiveRoundStatus",
  "isErrorRoundStatus",
  "isKeeperRoundActive",
  "isKeeperRoundSettlementPending",
  "isKeeperRoundTerminal",
  "isTerminalRoundStatus",
  "nativeXlmSacId",
  "parseMainnetManifest",
  "parseMainnetReadinessFixture",
  "readLiveDeployment",
  "networkFingerprint",
  "normalizeRoundId",
  "normalizeSorobanContractId",
  "parseReceipt",
  "redactReceipt",
  "roundStatusLabel",
  "runMainnetReadiness",
  "summarizeDeploymentValue",
  "serializeReceipt",
  "tryDecodeBase64",
  "tryDecodeHex",
  "validateAssetConfig",
  "validateAssetConfigs",
  "validateEncryptedBlob",
  "validateContractNetwork",
  "verifyReceipt",
  "verifySettledRoundProof",
];

describe("SDK public API snapshot", () => {
  it("should match the expected named exports", () => {
    const actual = Object.keys(sdk).sort();
    const expected = [...EXPECTED_EXPORTS].sort();
    assert.deepEqual(actual, expected);
  });
});
