// Copyright (c) 2026 Sub Rosa contributors
export {
  keepRound,
  closeRound,
  voidIfStale,
  discoverRoundIds,
  parseRoundIdSpec,
  watchRound,
  waitForRound,
  errorName,
  errorMatches,
  type KeeperDeps,
  type KeeperResult,
  type CloseResult,
  type VoidResult,
  type WatchTickResult,
  type KeeperLogger,
  type SkipRecord,
} from "./keeper.js";
export {
  createSettlementGuard,
  describeSettlementSkip,
  evaluateSettle,
  evaluateVoid,
  expectedWinner,
  readSettlementView,
  settleRefunds,
  voidRefunds,
  VOID_GRACE_SECONDS,
  type ClearingRuleTag,
  type ContractDecision,
  type ContractSkipEvent,
  type ContractSkipReason,
  type DuplicateSkipEvent,
  type GuardBidderState,
  type GuardSkipRecord,
  type RoundSettlementView,
  type SettlementAction,
  type SettlementCheck,
  type SettlementGuard,
  type SettlementGuardEntry,
  type SettlementGuardStatus,
  type SettlementPlan,
  type SettlementSkipEvent,
} from "./settlement-guard.js";
export {
  buildKeeperDryRunSummary,
  decideKeeperDryRunAction,
  parseKeeperRunConfig,
  type KeeperDryRunDecision,
  type KeeperDryRunPhase,
  type KeeperDryRunReader,
  type KeeperDryRunSummary,
  type KeeperRunConfig,
} from "./dry-run.js";
export {
  createStatusServer,
  withGracefulShutdown,
  bigintReplacer as statusBigintReplacer,
  type StatusServerConfig,
  type StatusServerHandle,
} from "./status-server.js";
export {
  buildKeeperStatus,
  buildRoundStatus,
  checkHealth,
  guardSkipIndicator,
  type BuildStatusSource,
  type BuildRoundStatusArgs,
  type StatusReader,
  type RoundStatus,
  type SettlementIndicator,
  type RoundStatusView,
  type KeeperServiceHealth,
  type KeeperStatusResponse,
} from "./status.js";
export { runWatchLoop, type RunWatchLoopParams } from "./watch-loop.js";
export { KeeperQueue, type KeeperQueueOptions } from "./queue.js";
export { KeeperStore, type WatchedRound, type RoundIdInput } from "./store.js";
